spring:
  mail:
    host: smtp.163.com
    username: 13260905180
    password: authForTss123
  datasource:
    url: jdbc:sqlite:onlineexam.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: com.enigmabridge.hibernate.dialect.SQLiteDialect
